spring.application.name=CRUD-futbol-apirest

# Conexion a MongoDB Atlas
spring.mongodb.uri=mongodb+srv://Gabriel_DB:UTS2026@cluster0.wws2n1k.mongodb.net/DB?retryWrites=true&w=majority
spring.mongodb.database=DB

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

server.port=8888
